#!/bin/sh

# To build mame as a library, use:
# ./batcab-make libmame

# You may also want to do:
# DEBUG=1 SYMBOLS=1 SUBTARGET=tiny ./batcab-make libmame
# The above will build a much smaller version of libmame with many fewer
# romsets supported but builds *alot* faster, which makes it good for testing.
# Also the above builds for debug.

# Finally you will probably be interested in the test program:
# DEBUG=1 SYMBOLS=1 SUBTARGET=tiny ./batcab-make libmame-test

if [ -z "$CONCURRENCY" ]; then
	CONCURRENCY=`cat /proc/cpuinfo | grep ^processor | wc -l`
	if [ -z "$CONCURRENCY" -o "$CONCURRENCY" = 0 ]; then
		CONCURRENCY=1
	else
		CONCURRENCY=$((CONCURRENCY*2))
	fi
fi

# MAME makefiles are DUMB and have dependencies on a phony maketree target
# that causes lots of targets to be rebuilt unnecessarily all of the time.
# For libmame, maketree is not depended on in this way, so that needless
# rebuilds don't happen all of the time; but since the maketree target must

OSD=libmame make -C `dirname $0` maketree
OSD=libmame NO_MAKETREE=1 make -j$((CONCURRENCY)) -C `dirname $0` "$@"
