#!/bin/sh

# To build mame as a library, use:
# OSD=lib ./batcab-make libmame.a
# You may also want to do:
# OST=lib SUBTARGET=tiny ./batcab-make libmame.a
# The above will build a much smaller version of libmame with many fewer
# romsets supported but builds *alot* faster, which makes it good for testing

NUM_PROCESSORS=`cat /proc/cpuinfo | grep ^processor | wc -l`

make -j$((NUM_PROCESSORS*2)) -C `dirname $0` "$@"
